service: social-care-workflows

variablesResolutionMode: 20210326
configValidationMode: error
frameworkVersion: ^2.59.0

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage}
  region: eu-west-2
  deploymentBucket:
    name: ${ssm:/${self:service}-${opt:stage}/deploy/bucket}
  role: ${ssm:/${self:service}-${opt:stage}/execution/role-arn}
  versionFunctions: true
  lambdaHashingVersion: 20201221
  ecr:
    images:
      application:
        path: ./
        buildArgs:
          NEXTAUTH_URL: https://${ssm:/${self:service}-${opt:stage}/domain/name}/
          NEXT_PUBLIC_GA_PROPERTY_ID: ${env:NEXT_PUBLIC_GA_PROPERTY_ID}
          NEXT_PUBLIC_SOCIAL_CARE_APP_URL: ${self:custom.social-care-urls.${opt:stage}}
          CSRF_SECRET: ${ssm:/${self:service}-${opt:stage}/environment/csrf-secret}

functions:
  nextjsServerless:
    timeout: 30
    image:
      name: application
      command: lambda.handler
    environment:
      ENVIRONMENT: ${opt:stage}
      DATABASE_URL: ${ssm:/${self:service}-${opt:stage}/database/url}
      NEXTAUTH_URL: https://${ssm:/${self:service}-${opt:stage}/domain/name}
      NEXT_PUBLIC_GA_PROPERTY_ID: ${env:NEXT_PUBLIC_GA_PROPERTY_ID}
      SESSION_SECRET: ${ssm:/${self:service}-${opt:stage}/environment/session-secret}
      CSRF_SECRET: ${ssm:/${self:service}-${opt:stage}/environment/csrf-secret}
      ALLOWED_DOMAIN: ${env:ALLOWED_DOMAIN}
      CONTENT_BUCKET: ${env:CONTENT_BUCKET}
      GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
      SOCIAL_CARE_API_ENDPOINT: ${env:SOCIAL_CARE_API_ENDPOINT}
      SOCIAL_CARE_API_KEY: ${env:SOCIAL_CARE_API_KEY}
      NEXT_PUBLIC_SOCIAL_CARE_APP_URL: ${env:NEXT_PUBLIC_SOCIAL_CARE_APP_URL}
      NOTIFY_API_KEY: ${env:NOTIFY_API_KEY}
      NOTIFY_APPROVER_TEMPLATE_ID: ${env:NOTIFY_APPROVER_TEMPLATE_ID}
      NOTIFY_RETURN_FOR_EDITS_TEMPLATE_ID: ${env:NOTIFY_RETURN_FOR_EDITS_TEMPLATE_ID}
      NOTIFY_NEXT_STEP_TEMPLATE_ID: ${env:NOTIFY_NEXT_STEP_TEMPLATE_ID}
      GSSO_TOKEN_NAME: ${env:GSSO_TOKEN_NAME}
      HACKNEY_JWT_SECRET: ${env:HACKNEY_JWT_SECRET}

    vpc:
      securityGroupIds:
        "Fn::Split":
          - ","
          - ${ssm:/${self:service}-${opt:stage}/execution/security-group-ids}
      subnetIds:
        "Fn::Split":
          - ","
          - ${ssm:/${self:service}-${opt:stage}/execution/subnet-ids}
    events:
      - http: ANY /
      - http: ANY /{proxy+}

  databaseMigrator:
    image:
      name: application
      command: migrate.handler
    timeout: 120
    environment:
      ENVIRONMENT: ${opt:stage}
      DATABASE_URL: ${ssm:/${self:service}-${opt:stage}/database/url}
    vpc:
      securityGroupIds:
        "Fn::Split":
          - ","
          - ${ssm:/${self:service}-${opt:stage}/execution/security-group-ids}
      subnetIds:
        "Fn::Split":
          - ","
          - ${ssm:/${self:service}-${opt:stage}/execution/subnet-ids}

  reportingExporter:
    image:
      name: application
      command: apps/reporting-exporter.handler
    timeout: 120
    environment:
      ENVIRONMENT: ${opt:stage}
      DATABASE_URL: ${ssm:/${self:service}-${opt:stage}/database/url}
      REPORTING_GOOGLE_EMAIL: ${env:REPORTING_GOOGLE_EMAIL}
      REPORTING_GOOGLE_PRIVATE_KEY: ${env:REPORTING_GOOGLE_PRIVATE_KEY}
    events:
      - schedule:
          enabled: true
          rate: cron(0 2 * * ? *)
          name: ${self:service}-${opt:stage}-reporting-exporter-event
    vpc:
      securityGroupIds:
        "Fn::Split":
          - ","
          - ${ssm:/${self:service}-${opt:stage}/execution/security-group-ids}
      subnetIds:
        "Fn::Split":
          - ","
          - ${ssm:/${self:service}-${opt:stage}/execution/subnet-ids}

  historicDataImporter:
    image:
      name: application
      command: apps/historic-data-importer.handler
    timeout: 120
    environment:
      ENVIRONMENT: ${opt:stage}
      DATABASE_URL: ${ssm:/${self:service}-${opt:stage}/database/url}
      HISTORIC_MAPPING_DATA_SOURCE: ${env:HISTORIC_MAPPING_DATA_SOURCE}
      SERVICE_USER_EMAIL: ${env:SERVICE_USER_EMAIL}
      SERVICE_USER_PRIVATE_KEY: ${env:SERVICE_USER_PRIVATE_KEY}
    events:
      - schedule:
          enabled: false
          rate: cron(0 2 * * ? *)
          name: ${self:service}-${opt:stage}-historic-data-importer-event
    vpc:
      securityGroupIds:
        "Fn::Split":
          - ","
          - ${ssm:/${self:service}-${opt:stage}/execution/security-group-ids}
      subnetIds:
        "Fn::Split":
          - ","
          - ${ssm:/${self:service}-${opt:stage}/execution/subnet-ids}

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - ${ssm:/${self:service}-${opt:stage}/domain/name}
          PriceClass: PriceClass_100
          ViewerCertificate:
            AcmCertificateArn: ${ssm:/${self:service}-${opt:stage}/domain/certificate}
            MinimumProtocolVersion: TLSv1.2_2018
            SslSupportMethod: sni-only
          DefaultCacheBehavior:
            TargetOriginId: ${self:service}-${self:provider.stage}-custom-origin
            ViewerProtocolPolicy: "redirect-to-https"
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
          Enabled: true
          Origins:
            - Id: ${self:service}-${self:provider.stage}-custom-origin
              DomainName:
                Fn::Join:
                  - "."
                  - - Ref: ApiGatewayRestApi
                    - execute-api
                    - ${self:provider.region}
                    - amazonaws.com
              OriginPath: /${self:provider.stage}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only

custom:
  social-care-urls:
    dev: https://social-care-service-staging.hackney.gov.uk
    stg: https://social-care-service-staging.hackney.gov.uk
    prod: https://social-care-service.hackney.gov.uk
