name: On push to main

on:
  push:
    branches: [main]

jobs:
  style-check:
    name: 💅 Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
          npm install prisma@$(cat package.json | jq '.dependencies.prisma' -r)

      - name: Generate prisma exports
        run: npm run build:prisma

      - name: Run lint
        run: npm run lint

      - name: Check types
        run: npm run typecheck

  tests-unit:
    name: 🧪 Unit tests
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_HOST: "http://localhost:3000"
      NEXTAUTH_URL: "http://localhost:3000"
      NODE_ENV: "test"
      NEXT_PUBLIC_ENV: "test"
      NEXT_PUBLIC_SOCIAL_CARE_APP_URL: "http://example.com"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
          npm install prisma@$(cat package.json | jq '.dependencies.prisma' -r)

      - name: Generate prisma exports
        run: npm run build:prisma

      - name: Run unit tests
        run: npm test
