name: On push to pull request

on: [pull_request]

jobs:
  export-reporting-data:
    name: Export reporting data
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prod
      AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}
      ALLOWED_DOMAIN: ${{ secrets.PRODUCTION_ALLOWED_DOMAIN }}
      CONTENT_BUCKET: ${{ secrets.PRODUCTION_CONTENT_BUCKET }}
      GOOGLE_CLIENT_ID: ${{ secrets.PRODUCTION_GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.PRODUCTION_GOOGLE_CLIENT_SECRET }}
      SOCIAL_CARE_API_ENDPOINT: ${{ secrets.PRODUCTION_SOCIAL_CARE_API_ENDPOINT }}
      SOCIAL_CARE_API_KEY: ${{ secrets.PRODUCTION_SOCIAL_CARE_API_KEY }}
      NEXT_PUBLIC_SOCIAL_CARE_APP_URL: ${{ secrets.PRODUCTION_NEXT_PUBLIC_SOCIAL_CARE_APP_URL }}
      NEXT_PUBLIC_GA_PROPERTY_ID: ${{ secrets.PRODUCTION_NEXT_PUBLIC_GA_PROPERTY_ID }}
      NOTIFY_API_KEY: ${{ secrets.PRODUCTION_NOTIFY_API_KEY }}
      NOTIFY_APPROVER_TEMPLATE_ID: ${{ secrets.PRODUCTION_NOTIFY_APPROVER_TEMPLATE_ID }}
      NOTIFY_RETURN_FOR_EDITS_TEMPLATE_ID: ${{ secrets.PRODUCTION_NOTIFY_RETURN_FOR_EDITS_TEMPLATE_ID }}
      NOTIFY_NEXT_STEP_TEMPLATE_ID: ${{ secrets.PRODUCTION_NOTIFY_NEXT_STEP_TEMPLATE_ID }}
      NOTIFY_ASSIGNEE_TEMPLATE_ID: ${{secrets.PRODUCTION_NOTIFY_ASSIGNEE_TEMPLATE_ID}}
      GSSO_TOKEN_NAME: ${{ secrets.GSSO_TOKEN_NAME }}
      HACKNEY_JWT_SECRET: ${{ secrets.HACKNEY_JWT_SECRET }}
      HISTORIC_MAPPING_DATA_SOURCE: ${{secrets.PRODUCTION_HISTORIC_MAPPING_DATA_SOURCE}}
      SERVICE_USER_PRIVATE_KEY: ${{secrets.PRODUCTION_SERVICE_USER_PRIVATE_KEY}}
      SERVICE_USER_EMAIL: ${{secrets.PRODUCTION_SERVICE_USER_EMAIL}}
      REPORTING_GOOGLE_EMAIL: ${{ secrets.PRODUCTION_REPORTING_GOOGLE_EMAIL }}
      REPORTING_GOOGLE_PRIVATE_KEY: ${{ secrets.PRODUCTION_REPORTING_GOOGLE_PRIVATE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Trigger reporting exporter lambda
        run: npm run remote:export:reporting-data
