name: Update form config from Contentful
on:
  repository_dispatch:
    types:
      - forms_changed
jobs:
  update-forms:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta

      - name: Install dependencies
        run: npm i

      - name: Update form config
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        run: npm run import:contentful:forms

      - name: Commit changes
        continue-on-error: true
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add config/forms/forms.json
          git commit -m "Updated form data from Contentful"
          git push origin main
