name: Update content files
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/upload-content-files.yml
  repository_dispatch:
    types:
      - content_changed

jobs:
  commit-updated-content:
    runs-on: ubuntu-latest
    concurrency: content-commit
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: git pull -r

      - name: Install dependencies
        run: npm ci

      - name: Update content config i.e forms, answer filters and next steps
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        run: |
          npm run import:contentful:forms
          npm run import:contentful:answer-filters
          npm run import:contentful:next-steps

      - name: Commit content changes
        continue-on-error: true
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add config/forms/forms.json
          git add config/answerFilters/answerFilters.json
          git add config/nextSteps/nextStepOptions.json
          git commit -m "Updated content data from Contentful"
          git push origin main

  push-content-to-staging:
    name: 🛳 Push updated content changes to S3 (Staging)
    runs-on: ubuntu-latest
    concurrency: content-staging
    needs:
      - commit-updated-content
    environment:
      name: Content - Staging
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-2
      BUCKET: ${{ secrets.STAGING_CONTENT_BUCKET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: git pull -r
      - run: aws s3 cp ./config/forms/forms.json "s3://$BUCKET/forms.json"
      - run: aws s3 cp ./config/answerFilters/answerFilters.json "s3://$BUCKET/answerFilters.json"
      - run: aws s3 cp ./config/nextSteps/nextStepOptions.json "s3://$BUCKET/nextStepOptions.json"

  push-content-to-production:
    name: 🚀 Push updated content changes to S3 (Production)
    runs-on: ubuntu-latest
    concurrency: content-production
    needs:
      - push-content-to-staging
    environment:
      name: Content - Production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-2
      BUCKET: ${{ secrets.PRODUCTION_CONTENT_BUCKET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: git pull -r
      - run: aws s3 cp ./config/forms/forms.json "s3://$BUCKET/forms.json"
      - run: aws s3 cp ./config/answerFilters/answerFilters.json "s3://$BUCKET/answerFilters.json"
      - run: aws s3 cp ./config/nextSteps/nextStepOptions.json "s3://$BUCKET/nextStepOptions.json"
