name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
      NEXT_PUBLIC_API_HOST: "http://localhost:3000"
      NEXTAUTH_URL: "http://localhost:3000"
      NODE_ENV: "test"
      NEXT_PUBLIC_ENV: "test"
      NEXT_PUBLIC_SOCIAL_CARE_APP_URL: "http://example.com"
      PORT: "3000"

    steps:
      - uses: actions/checkout@v2

      - name: Set up test database
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "11"
          postgresql db: "postgres"
          postgresql user: "postgres"
          postgresql password: "postgres"

      - name: Install dependencies
        run: npm i

      - name: Apply database schema
        run: npm run db:push

      - name: Seed database
        run: npm run db:seed

      - name: Build app
        run: npm run build

      - name: Start
        run: npm start
